mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: Birdy0515.
  database: myblog
  level: ""
logger:
    level: info
    prefix: '[blog]'
    direct: ./logs
    showLine: false
    logInConsole: false
system:
    host: 0.0.0.0
    port: 8080
    env: debug # debug release